spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:pictgram
    username: sa
    password: 

  h2:
    console:
      enabled: true
      spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
        
        servret:
        multipart:
        max-file-size: 20MB
        max-repuest-size: 20MB
        
        image:
    local: true